import React from "react";
export const AdminDashboard = React.lazy(() => import("./AdminDashboard/index.page"));
export const AdminMasters = React.lazy(() => import("./AdminMasters/index.page"));
export const AdminCompany = React.lazy(() => import("./AdminCompany/index.page"));
export const AdminCompanyAdd = React.lazy(() => import("./AdminCompanyAdd/index.page"));
export const AdminCountry = React.lazy(() => import("./AdminCountry/index.page"));
export const AdminState = React.lazy(() => import("./AdminState/index.page"));
export const AdminCity = React.lazy(() => import("./AdminCity/index.page"));
export const AdminFinancialYear = React.lazy(() => import("./AdminFinancialYear/index.page"));
export const AdminAccountGroupHead = React.lazy(() => import("./AdminGroupHead/index.page"));
export const AdminAccountHead = React.lazy(() => import("./AdminHead/index.page"));
export const AdminAccountHeadAdd = React.lazy(() => import("./AdminHeadAdd/index.page"));
export const AdminRoleMasters = React.lazy(() => import("./AdminRoleMaster/index.page"));
export const AdminEmployeeAdd = React.lazy(() => import("./AdminEmployeeAdd/index.page"));
export const AdminEmployee = React.lazy(() => import("./AdminEmployee/index.page"));
export const AdminSallaryHeadSetup = React.lazy(() => import("./AdminSallaryHeadSetup/index.page"));
export const AdminLeaveRequest = React.lazy(() => import("./AdminLeaveRequest/index.page"));