import superAdminRouteMap from "../superAdminRouteMap";
import { AdminDashboard, AdminMasters, AdminCompany, AdminCompanyAdd, AdminCountry, AdminState, AdminCity, AdminFinancialYear, AdminAccountGroupHead, AdminAccountHead, AdminAccountHeadAdd, AdminRoleMasters, AdminEmployee, AdminEmployeeAdd, AdminLeaveRequest, AdminEmployeeWiseSallaryHeadSetup, AdminEmployeeWiseSallaryHeadSetupAdd, AdminSallaryHead, AdminHoliday } from "../../../pages/SuperAdmin";

export default function route() {
  return [
    {
      path: superAdminRouteMap.DASHBOARD.path,
      key: superAdminRouteMap.DASHBOARD.path,
      name: "Admin Profile",
      private: true,
      element: <AdminDashboard />,
    },
    {
      path: superAdminRouteMap.MASTERS.path,
      key: superAdminRouteMap.MASTERS.path,
      name: "Masters",
      private: true,
      element: <AdminMasters />,
    },
    {
      path: superAdminRouteMap.COMPANY.path,
      key: superAdminRouteMap.COMPANY.path,
      name: "Company",
      private: true,
      element: <AdminCompany />,
    },
    {
      path: superAdminRouteMap.COMPANY_ADD.path,
      key: superAdminRouteMap.COMPANY_ADD.path,
      name: "Company Add",
      private: true,
      element: <AdminCompanyAdd />,
    },
    {
      path: superAdminRouteMap.COUNTRY.path,
      key: superAdminRouteMap.COUNTRY.path,
      name: "Country",
      private: true,
      element: <AdminCountry />,
    },
    {
      path: superAdminRouteMap.STATE.path,
      key: superAdminRouteMap.STATE.path,
      name: "State",
      private: true,
      element: <AdminState />,
    },
    {
      path: superAdminRouteMap.CITY.path,
      key: superAdminRouteMap.CITY.path,
      name: "City",
      private: true,
      element: <AdminCity />,
    },
    {
      path: superAdminRouteMap.FINANCIAL_YEAR.path,
      key: superAdminRouteMap.FINANCIAL_YEAR.path,
      name: "Financial Year",
      private: true,
      element: <AdminFinancialYear />,
    },
    {
      path: superAdminRouteMap.ACCOUNT_GROUP_HEAD.path,
      key: superAdminRouteMap.ACCOUNT_GROUP_HEAD.path,
      name: "Account Group Head",
      private: true,
      element: <AdminAccountGroupHead />,
    },
    {
      path: superAdminRouteMap.ACCOUNT_HEAD.path,
      key: superAdminRouteMap.ACCOUNT_HEAD.path,
      name: "Account Head",
      private: true,
      element: <AdminAccountHead />,
    },
    {
      path: superAdminRouteMap.ACCOUNT_HEAD_ADD.path,
      key: superAdminRouteMap.ACCOUNT_HEAD_ADD.path,
      name: "Account Head Add",
      private: true,
      element: <AdminAccountHeadAdd />,
    },
    {
      path: superAdminRouteMap.ROLE.path,
      key: superAdminRouteMap.ROLE.path,
      name: "Account Head Add",
      private: true,
      element: <AdminRoleMasters />,
    },
    {
      path: superAdminRouteMap.EMPLOYEE.path,
      key: superAdminRouteMap.EMPLOYEE.path,
      name: "Employee",
      private: true,
      element: <AdminEmployee />,
    },
    {
      path: superAdminRouteMap.LEAVE_REQUEST.path,
      key: superAdminRouteMap.LEAVE_REQUEST.path,
      name: "Employee Leave Request",
      private: true,
      element: <AdminLeaveRequest />,
    },
    {
      path: superAdminRouteMap.EMPLOYEE_ADD.path,
      key: superAdminRouteMap.EMPLOYEE_ADD.path,
      name: "Employee Add",
      private: true,
      element: <AdminEmployeeAdd />,
    },
    {
      path: superAdminRouteMap.SALLARY_HEAD_SETUP_ADD.path,
      key: superAdminRouteMap.SALLARY_HEAD_SETUP_ADD.path,
      name: "Employee Sallary Head Setup Add",
      private: true,
      element: <AdminEmployeeWiseSallaryHeadSetupAdd />,
    },
    {
      path: superAdminRouteMap.SALLARY_HEAD_SETUP.path,
      key: superAdminRouteMap.SALLARY_HEAD_SETUP.path,
      name: "Employee Sallary Head Setup",
      private: true,
      element: <AdminEmployeeWiseSallaryHeadSetup />,
    },
    {
      path: superAdminRouteMap.SALLARY_HEAD.path,
      key: superAdminRouteMap.SALLARY_HEAD.path,
      name: "Sallary Head Setup",
      private: true,
      element: <AdminSallaryHead />,
    },
    {
      path: superAdminRouteMap.HOLIDAY.path,
      key: superAdminRouteMap.HOLIDAY.path,
      name: "Holiday",
      private: true,
      element: <AdminHoliday />,
    },
  ];
}
